apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: rt1ao9v1m-python 
  janus-idp.io/tekton: rt1ao9v1m-python
  backstage.io/kubernetes-id: rt1ao9v1m-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: rt1ao9v1m-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml