apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: rt1ao9v1m-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rt1ao9v1m-python 
  name: rt1ao9v1m-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: rt1ao9v1m-python 
