apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: rt1ao9v1m-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-python:44b54cb09b7bb2aedc57bb6c0fcfefcc75eac7f2@sha256:30d1d88094c09ccf17bee4eba6a968889935910e2148efa82c8738a0bd122c97
          name: container-image
